apiVersion: v1
kind: Service
metadata:
  name: front-znjh-svc
  namespace: jt-ecloud-test
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: front-znjh
